services:
  - type: web
    name: web-access-check-backend
    env: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y chromium-browser
      npm install
    startCommand: npm run dev
    environment:
      NODE_ENV: production
      CHROME_PATH: /usr/bin/chromium-browser
